# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: subscription.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='subscription.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12subscription.proto\"3\n\x10\x46ieldConfigType1\x12\x10\n\x08operator\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\t\"3\n\x10\x46ieldConfigType2\x12\x10\n\x08operator\x18\x01 \x02(\t\x12\r\n\x05value\x18\x02 \x02(\x05\"\xcf\x01\n\x0cSubscription\x12$\n\tcar_model\x18\x01 \x01(\x0b\x32\x11.FieldConfigType1\x12*\n\x0fproduction_date\x18\x02 \x01(\x0b\x32\x11.FieldConfigType1\x12%\n\nhorsepower\x18\x03 \x01(\x0b\x32\x11.FieldConfigType2\x12 \n\x05\x63olor\x18\x04 \x01(\x0b\x32\x11.FieldConfigType1\x12$\n\tmax_speed\x18\x05 \x01(\x0b\x32\x11.FieldConfigType2'
)




_FIELDCONFIGTYPE1 = _descriptor.Descriptor(
  name='FieldConfigType1',
  full_name='FieldConfigType1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operator', full_name='FieldConfigType1.operator', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='FieldConfigType1.value', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=73,
)


_FIELDCONFIGTYPE2 = _descriptor.Descriptor(
  name='FieldConfigType2',
  full_name='FieldConfigType2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operator', full_name='FieldConfigType2.operator', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='FieldConfigType2.value', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=126,
)


_SUBSCRIPTION = _descriptor.Descriptor(
  name='Subscription',
  full_name='Subscription',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='car_model', full_name='Subscription.car_model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='production_date', full_name='Subscription.production_date', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='horsepower', full_name='Subscription.horsepower', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='color', full_name='Subscription.color', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='max_speed', full_name='Subscription.max_speed', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=336,
)

_SUBSCRIPTION.fields_by_name['car_model'].message_type = _FIELDCONFIGTYPE1
_SUBSCRIPTION.fields_by_name['production_date'].message_type = _FIELDCONFIGTYPE1
_SUBSCRIPTION.fields_by_name['horsepower'].message_type = _FIELDCONFIGTYPE2
_SUBSCRIPTION.fields_by_name['color'].message_type = _FIELDCONFIGTYPE1
_SUBSCRIPTION.fields_by_name['max_speed'].message_type = _FIELDCONFIGTYPE2
DESCRIPTOR.message_types_by_name['FieldConfigType1'] = _FIELDCONFIGTYPE1
DESCRIPTOR.message_types_by_name['FieldConfigType2'] = _FIELDCONFIGTYPE2
DESCRIPTOR.message_types_by_name['Subscription'] = _SUBSCRIPTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FieldConfigType1 = _reflection.GeneratedProtocolMessageType('FieldConfigType1', (_message.Message,), {
  'DESCRIPTOR' : _FIELDCONFIGTYPE1,
  '__module__' : 'subscription_pb2'
  # @@protoc_insertion_point(class_scope:FieldConfigType1)
  })
_sym_db.RegisterMessage(FieldConfigType1)

FieldConfigType2 = _reflection.GeneratedProtocolMessageType('FieldConfigType2', (_message.Message,), {
  'DESCRIPTOR' : _FIELDCONFIGTYPE2,
  '__module__' : 'subscription_pb2'
  # @@protoc_insertion_point(class_scope:FieldConfigType2)
  })
_sym_db.RegisterMessage(FieldConfigType2)

Subscription = _reflection.GeneratedProtocolMessageType('Subscription', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTION,
  '__module__' : 'subscription_pb2'
  # @@protoc_insertion_point(class_scope:Subscription)
  })
_sym_db.RegisterMessage(Subscription)


# @@protoc_insertion_point(module_scope)
